name: Get NY Times puzzle links

on:
  schedule:
    - cron: '2 * * * *'
  push:
    branches: [ master ]


# A workflow run is made up of one or more jobs
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Run Python stuff
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4
    - name: Run Sudoku
      run: |
        python sudoku.py

    # Run Node stuff
    - name: Set up Node
      uses: actions/setup-node@v1
      with:
        node-version: 14
    - run: npm install
    - run: node index.js

    
