name: Get Sudoku puzzle links

on:
  schedule:
    - cron: '5 4/6 * * *'
  push:
    branches: [ master ]

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    # Check out code
    - uses: actions/checkout@v2

    # Run Python stuff
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4
    - name: Run Python scraper
      run: python sudoku.py >> puzzle_output.txt

    # Run Node stuff
    - name: Set up Node
      uses: actions/setup-node@v1
      with:
        node-version: 14
    - run: npm install
    - name: Run Node scraper
      run: node index.js >> puzzle_output.txt

    # Show everything (temporary)
    - name: List puzzle output
      run: cat puzzle_output.txt

    - name: Upload puzzle output
      uses: actions/upload-artifact@v1
      with:
        name: out
        path: puzzle_output.txt

